# Generated by Django 3.2.19 on 2023-06-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItems',
        ),
    ]
