# Generated by Django 3.2.19 on 2023-06-04 08:23

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_delete_todoitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=projects.models.one_week_hence)),
            ],
        ),
    ]
